version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "15:05"  # 12:05pm Brasilia/Brazil
